inherit_gem:
  caliber: config/all.yml

plugins: rubocop-sequel

Metrics/BlockLength:
  Exclude:
    - config/db/migrate/*
Metrics/CyclomaticComplexity:
  AllowedMethods:
    - battery_percentage
    - wifi_percentage
Metrics/MethodLength:
  AllowedMethods:
    - battery_percentage
    - wifi_percentage
  Exclude:
    - app/views/helpers.rb
RSpec/ExampleLength:
  Exclude:
    - "spec/features/**/*"
RSpec/SpecFilePathFormat:
  CustomTransform:
    Terminus: ""
Style/IpAddresses:
  Exclude:
    - spec/**/*
